-- 配置基础设置
require "user.options"
-- 配置键盘设置
require "user.keymaps"
-- 配置插件
require "user.plugins"
-- 配置颜色主题
require "user.colorscheme"
-- 配置代码片段
require "user.cmp"
-- 语言服务器，用于补全，需要搭配cmp
require "user.lsp"
-- 寻找文件的插件
require "user.telescope"
-- github的插件
require "user.gitsigns"
-- 用于语法高亮的插件，自定义哪些高亮
require "user.treesitter"
-- 自动括号插件
require "user.autopairs"
-- 注释插件
require "user.comment"
-- 目录树插件
require "user.nvim-tree"
-- 头上的窗口标号插件
require "user.bufferline"
--
require "user.lualine"
-- 可以启动终端插件
require "user.toggleterm"
-- 工程管理
require "user.project"
-- 
require "user.impatient"
-- 
require "user.indentline"
-- 启动目录的设置
require "user.alpha"
-- 键盘绑定
require "user.whichkey"
-- 根据文件自动注释
require "user.autocommands"
-- debugger
require "user.dap"
-- OUTLINE 
require "user.outline"
-- TODO
require "user.todo"
-- NOICE
require "user.noice"
-- NOTIFY
-- require "user.notify"
